### ISSUE TITLE
1.0.9 broke everything

### ISSUE THREAD

**Issue by Ogge66** [Charlie-Root/homey-nl-verisure#23]
What happened?! 1.0.8 worked awesome and now (forgot to turn off auto-update) my alarm driver doesn't detect when It's armed or disarmed anymore. So dissappointed!!!

**Comment by fredrikjohnsson** [comment]
I've got that issue as well for version 1.0.9.

**Comment by deepvalleySE** [comment]
Just adding for helping the developer to find the issue: In my case, 1.0.9 works but with a very long delay. From arming/disarming it takes 3-4 minutes for Homey to know. Have checked about five times and the time span seems to be the same every time.

With 1.0.8 it took seconds, between 1-5 is my impression, and that worked without Verisure taking any action for weeks.

**Comment by fredrikjohnsson** [comment]
I've actually also noticed that now that it takes a long time before alarm state changes.

**Comment by Charlie-Root** [comment]
very attentive. In 1.0.9 the timer has been set to 5 minutes in order to avoid the block from verisure. 

In regards to the alarm driver: this isn't the delay you are seeing? is it not working at all ?

**Comment by deepvalleySE** [comment]
For me it works, but with the delay you've set in 1.0.9. Sorry if I hijacked Ogge66's original question.

Just a quick continued hijacking though :) I had no issues at all with Verisure after 1.0.8. Perhaps because I decided to only include the alarm driver and skip contact sensors etc in order to minimize the number of requests. One suggestion would be to allow each individual user to set whatever limit they prefer, perhaps from 10 seconds and up - and include a warning to not go bananas with devices.

**Comment by henkson12** [comment]
Just got my first brand new shiny Homey.
Not able to login.
Works fine in both app and web.

**Comment by JohanLagergren** [comment]
Me to can't log in with the app in Homey. Latest Homey update installed.

**Comment by Charlie-Root** [comment]
version 1.2.0 will be pushed in a few days resolving that.
