### ISSUE TITLE
Instructions here or on Homey App page?

### ISSUE THREAD

**Issue by aakerman** [Charlie-Root/homey-nl-verisure#43]
Hi,
not a software issue, more about information.
Installation process and setting up would benefit from some more details, here and in the Homey App page.

1. Does this work with Yale Doorman V2 or V2N Verisure lock remote unit or both versions? 
2. Do you need a Verisure Mikro unit in order to run this or is Homey app supposed to talk directly to the Verisure remote unit inside the door w Yale Doorman. // Installing this app without the Verisure Mikro unit renders the adding device in Homey to just run a cogwheel - like it's searching for something - without any explanation.
3. Yale and some other third party vendors are now selling a remote unit (for installation in the door lock). Indications I have is that the Yale and others do NOT talk to Verisure, but you actually need Verisure own remote unit. Verisure support confirms this in Nov. 2018. Please clarify if such knowledge exists. Most resellers of these items are very clueless. I guess since all these things are fairly new. :-)
4. On Homey, after supplied login credentials for Verisure, there is a question on Passcode - some clarification on the page on what passcode this is. For the door? Other?

**Comment by Charlie-Root** [comment]
Hi Aakerman,

Thank you for using the Verisure app. I maintain this app because I am using Verisure (alarm) myself and after publication added some devices and features on request. This means not everything is supported.

I will anwser the questions as well as possible;
1. No idea, they do not sell this in The Netherlands and so i cannot test or check. Support for the Yale Doorman was a feature request, if i have access i can alter/add it. 
2. The Homey Verisure app uses the Mobile API. If there is a function you have in the Verisure app, we can make it work from Homey as well. I do not have this hardware to test.
3. I have not heared about this before and i do not use the lock function. Not clear on this.
4. Will add some fancy description. It is however the door code (for setting or disarming the alarm).

**Comment by aakerman** [comment]
Great replies. Much appreciated! #1 - I saw that discussion and understand.
Good work so far. Thank you.
